### ISSUE TITLE
Raspberry Crash when running the Script

### ISSUE THREAD

**Issue by Brudertac** [dslotter/ham_radio_scripts#1]
Running the Script "update_fldigi_suite" on a RaspberryPi 4b with 8GB crash the Pi complete.

Installed is HamPI 3.0.1. i also run "sudo apt-get dist-upgrade" with an Reboot before i run the Script.

Many Thanks and best Regards!

**Comment by dslotter** [comment]
@Brudertac What do you mean "crash the Pi complete"? Can you provide more specifics, as in any error messages? Maybe a screen capture?

**Comment by Brudertac** [comment]
@dslotter 
Thanks for your Reply. 
The Pi crashes and i have to disconnect Power from it to Restart it.

Here is a Screenshot from VNC Viewer when it is crashed.

![image](https://user-images.githubusercontent.com/25863131/189134365-e16cb3b6-7d3c-455c-93ac-bc1c9b4c93c9.png)


> @Brudertac What do you mean "crash the Pi complete"? Can you provide more specifics, as in any error messages? Maybe a screen capture?

**Comment by dslotter** [comment]
@Brudertac:

1. Do you know the temperature of the Pi 4B 8GB at the time of the crash?
2. Do you have any heat sinks installed on the Pi 4B 8GB?
3. Do you have a fan installed on the Pi 4B 8GB?
4. Have you made any modifications to HamPi 3.0.1?

**Comment by dslotter** [comment]
> @dslotter Thanks for your Reply. The Pi crashes and i have to disconnect Power from it to Restart it.
> 
> Here is a Screenshot from VNC Viewer when it is crashed.
> 
> ![image](https://user-images.githubusercontent.com/25863131/189134365-e16cb3b6-7d3c-455c-93ac-bc1c9b4c93c9.png)
> 
> > @Brudertac What do you mean "crash the Pi complete"? Can you provide more specifics, as in any error messages? Maybe a screen capture?

So I have reviewed this output and this is not output that this script would ever generate. If I had to guess, this is from building Hamlib, which this script does not do. Please refer to the heat-related questions above. That would be the first thing I would look at. Thanks and good luck.
